# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/robwork/RobWorkStudio/example/Rob2Project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/robwork/RobWorkStudio/example/Rob2Project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/robwork/RobWorkStudio/example/Rob2Project2/CMakeFiles /home/daniel/robwork/RobWorkStudio/example/Rob2Project2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/robwork/RobWorkStudio/example/Rob2Project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Rob2Project2Plugin

# Build rule for target.
Rob2Project2Plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Rob2Project2Plugin
.PHONY : Rob2Project2Plugin

# fast build rule for target.
Rob2Project2Plugin/fast:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/build
.PHONY : Rob2Project2Plugin/fast

Rob2Project2Plugin.o: Rob2Project2Plugin.cpp.o
.PHONY : Rob2Project2Plugin.o

# target to build an object file
Rob2Project2Plugin.cpp.o:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/Rob2Project2Plugin.cpp.o
.PHONY : Rob2Project2Plugin.cpp.o

Rob2Project2Plugin.i: Rob2Project2Plugin.cpp.i
.PHONY : Rob2Project2Plugin.i

# target to preprocess a source file
Rob2Project2Plugin.cpp.i:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/Rob2Project2Plugin.cpp.i
.PHONY : Rob2Project2Plugin.cpp.i

Rob2Project2Plugin.s: Rob2Project2Plugin.cpp.s
.PHONY : Rob2Project2Plugin.s

# target to generate assembly for a file
Rob2Project2Plugin.cpp.s:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/Rob2Project2Plugin.cpp.s
.PHONY : Rob2Project2Plugin.cpp.s

moc_Rob2Project2Plugin.o: moc_Rob2Project2Plugin.cxx.o
.PHONY : moc_Rob2Project2Plugin.o

# target to build an object file
moc_Rob2Project2Plugin.cxx.o:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/moc_Rob2Project2Plugin.cxx.o
.PHONY : moc_Rob2Project2Plugin.cxx.o

moc_Rob2Project2Plugin.i: moc_Rob2Project2Plugin.cxx.i
.PHONY : moc_Rob2Project2Plugin.i

# target to preprocess a source file
moc_Rob2Project2Plugin.cxx.i:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/moc_Rob2Project2Plugin.cxx.i
.PHONY : moc_Rob2Project2Plugin.cxx.i

moc_Rob2Project2Plugin.s: moc_Rob2Project2Plugin.cxx.s
.PHONY : moc_Rob2Project2Plugin.s

# target to generate assembly for a file
moc_Rob2Project2Plugin.cxx.s:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/moc_Rob2Project2Plugin.cxx.s
.PHONY : moc_Rob2Project2Plugin.cxx.s

qrc_resources.o: qrc_resources.cxx.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cxx.o:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/qrc_resources.cxx.o
.PHONY : qrc_resources.cxx.o

qrc_resources.i: qrc_resources.cxx.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cxx.i:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/qrc_resources.cxx.i
.PHONY : qrc_resources.cxx.i

qrc_resources.s: qrc_resources.cxx.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cxx.s:
	$(MAKE) -f CMakeFiles/Rob2Project2Plugin.dir/build.make CMakeFiles/Rob2Project2Plugin.dir/qrc_resources.cxx.s
.PHONY : qrc_resources.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Rob2Project2Plugin"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Rob2Project2Plugin.o"
	@echo "... Rob2Project2Plugin.i"
	@echo "... Rob2Project2Plugin.s"
	@echo "... moc_Rob2Project2Plugin.o"
	@echo "... moc_Rob2Project2Plugin.i"
	@echo "... moc_Rob2Project2Plugin.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

